apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/instance: keto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keto
    app.kubernetes.io/version: v0.6.0
    helm.sh/chart: keto-0.19.3
  name: keto-automigrate
  namespace: identity
spec:
  backoffLimit: 10
  completions: 1
  parallelism: 1
  template:
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - migrate
        - up
        - -y
        - --config
        - /etc/config/keto.yaml
        command:
        - keto
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              key: dsn
              name: keto
        image: oryd/keto:latest
        imagePullPolicy: IfNotPresent
        name: keto-automigrate
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 100
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: keto-config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: keto-config
        name: keto-config-volume
