# Default values for kratos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 30%
    maxUnavailable: 0 

image:
  repository: oryd/kratos
  tag: latest #v0.6.3-alpha.1
  pullPolicy: IfNotPresent
# Alternative format
# image: oryd/kratos:v0.6.3-alpha.1
# imagePullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  admin:
    enabled: true
    type: ClusterIP
    port: 80
    # If you do want to specify annotations, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
    annotations: 
      kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  

secret:
  # switch to false to prevent creating the secret
  enabled: false
  # ... and choose a different name for a secret you provide like this
  nameOverride: kratos

ingress:
  admin:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: id.vonage.k8s.local
        paths:
        - path: "/idp-admin(/|$)(.*)"
          pathType: ImplementationSpecific

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
 
kratos:
  development: false
  # Enable the initialization job. Required to work with a DB
  autoMigrate: true
  identitySchemas:
    "login.jsonnet": |
      function(ctx) {
        flow_id: ctx.flow.id,
        identity_id: if ctx["identity"] != null then ctx.identity.id,
        headers: ctx.request_headers,
        url: ctx.request_url,
        method: ctx.request_method,
        __raw: ctx
      }
    "identity.default.schema.json": |
      {
         "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
         "$schema": "http://json-schema.org/draft-07/schema#",
         "title": "Person",
         "type": "object",
         "properties": {
            "traits": {
               "type": "object",
               "properties": {
                  "email": {
                     "type": "string",
                     "format": "email",
                     "title": "E-Mail",
                     "ory.sh/kratos": {
                        "credentials": {
                           "password": {
                              "identifier": true
                           }
                        },
                        "recovery": {
                           "via": "email"
                        },
                        "verification": {
                           "via": "email"
                        }
                     }
                  }
               },
               "required": [
                  "email"
               ],
               "additionalProperties": false
            }
         }
      }
#  You can add multiple identity schemas here
#  identitySchemas:
#    "identity.default.schema.json": |
#      {
#        // ...
#      }
#    "identity.email.schema.json": |
#      {
#        // ...
#      }

#  You can customize the emails kratos is sending (also uncomment config.courier.template_override_path below)
#  Note: If you are setting config.courier.template_override_path you need to supply overrides for all templates.
#        It is currently not possible to overrides only selected methods.
#
#  emailTemplates:
#    recovery:
#      valid:
#        subject: Recover access to your account
#        body: |-
#          Hi, please recover access to your account by clicking the following link:
#
#          <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a>
#        plainBody: Hi, please recover access to your account by clicking the following link: {{ .RecoveryURL }}
#      invalid:
#        subject: Account access attempted
#        body: |-
#          Hi, you (or someone else) entered this email address when trying to recover access to an account.
#
#          However, this email address is not on our database of registered users and therefore the attempt has failed. If this was you, check if you signed up using a different address. If this was not you, please ignore this email.
#        plainBody: Hi, you (or someone else) entered this email address when trying to recover access to an account.
#    verification:
#      valid:
#        subject: Please verify your email address
#        body: |-
#          Hi, please verify your account by clicking the following link:
#
#          <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a>
#        plainBody: Hi, please verify your account by clicking the following link: {{ .RecoveryURL }}
#      invalid:
#        subject:
#        body:
#        plainBody:

  config:
    serve:
      public:
        port: 4433
        base_url: https://id.vonage.k8s.local/idp
        cors:
          enabled: true
      admin:
        port: 4434
        base_url: https://id.vonage.k8s.local/idp-admin
    dsn: cockroach://root:root@cockroach-cockroachdb-public.identity:26257/kratos
    selfservice:
      default_browser_return_url: https://id.vonage.k8s.local/ui/dashboard
      whitelisted_return_urls:
      - https://id.vonage.k8s.local/ui/dashboard
      methods:
        password:
          enabled: true
        oidc:
          enabled: true
        profile:
          enabled: true
        link:
          enabled: true
      flows:
        recovery:
          enabled: true
          lifespan: 15m
          ui_url: https://id.vonage.k8s.local/ui/recovery
        settings:
          privileged_session_max_age: 1m
          ui_url: https://id.vonage.k8s.local/ui/settings
        login:
          ui_url: https://id.vonage.k8s.local/ui/auth/login
          lifespan: 100m
          after:
            password:
              hooks:
                - hook: web_hook
                  config:
                    url: http://localhost:3500/v1.0/publish/audit/VIAM
                    method: POST
                    body: /etc/config/login.jsonnet
        logout:
          after:
            default_browser_return_url: https://id.vonage.k8s.local/ui/auth/login
        registration:
          lifespan: 10m
          ui_url: https://id.vonage.k8s.local/ui/auth/registration
          after:
            password:
              hooks:
              - hook: session
              - hook: web_hook
                config:
                  url: http://localhost:3500/v1.0/publish/audit/VIAM
                  method: POST
                  body: /etc/config/login.jsonnet
        verification:
          enabled: true
          ui_url: https://id.vonage.k8s.local/ui/verify
        error:
          ui_url: https://id.vonage.k8s.local/ui/error
    log:
      level: info
      format: json
      leak_sensitive_values: true
    secrets:
      session:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
    hashers:
      argon2:
        parallelism: 1
        memory: 128MB
        iterations: 2
        salt_length: 16
        key_length: 16
    identity:
      default_schema_url: file:///etc/config/identity.default.schema.json
    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

deployment:
   # Configure the probes for when the deployment is considered ready and ongoing health check
  livenessProbe:
    httpGet:
      path: /health/alive
      port: http-admin
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /health/ready
      port: http-admin
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5

  extraEnv: []
 

  labels: {}
  #      If you do want to specify additional labels, uncomment the following
  #      lines, adjust them as necessary, and remove the curly braces after 'labels:'.
  #      e.g.  type: app

  annotations: 
    dapr.io/app-id: "kratos-admin"
    dapr.io/enabled: "true"
    dapr.io/config: "vonage"
    dapr.io/app-port: "4434" #Must equal .Values.kratos.config.serve.public.port
  #      If you do want to specify annotations, uncomment the following
  #      lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
  #      e.g.  sidecar.istio.io/rewriteAppHTTPProbers: "true"

  # The secret specified here will be used to load environment variables with envFrom.
  # This allows arbitrary environment variables to be provided to the application which is useful for
  # sensitive values which should not be in a configMap.
  # This secret is not created by the helm chart and must already exist in the namespace.
  # https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables
  # environmentSecretsName:

  # https://github.com/kubernetes/kubernetes/issues/57601
  automountServiceAccountToken: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 100
  allowPrivilegeEscalation: false
  privileged: false

